Change error handling logic in db.close()
etcd-io/bbolt pull request #400
Opened 2023-02-04 00:06 UTC by CaojiamingAlan

https://github.com/etcd-io/bbolt/issues/382#issuecomment-1414774101
Complete all cleanup operations in db.close() even if there is an error in the middle. Otherwise fd remains open and flock is not released.

Add a test mocking the munmap syscall fails. This test fails before this commit.

2023-02-05 23:34 UTC, ahrtr commented on db.go
> +	var errs []string
```suggestion
	var errs []error
```

I suggest to only return the first error if present. It is consistent with the existing behavior. We will add log in separate PR to record all errors.

2023-02-05 23:34 UTC, ahrtr commented
Please signoff the commit:
```
$ git rebase HEAD~1 --signoff
$ git push origin release-lock-on-unmap-error -f
```

2023-02-09 21:48 UTC, ahrtr commented on db.go
> +	var errs []string
Please resolve this comment: change the type to `[]error`. It doesn't make sense to convert the errors to strings, and finally convert them back to errors.

2023-02-10 05:26 UTC, ahrtr approved these changes
LGTM

Thank you @CaojiamingAlan

2023-02-10 05:36 UTC, ahrtr requested changes
Please resolve the workflow error.

2023-02-10 15:46 UTC, ptabor approved these changes
Thank you. Looks good to me. Let's see whether the test passes.

2023-02-10 23:20 UTC, ahrtr approved these changes
Thanks again. 

Could you backport this PR to [release-1.3](https://github.com/etcd-io/bbolt/tree/release-1.3)?

2023-02-10 23:21 UTC, merged