etcd: upgrade go version from 1.21.4
etcd-io/bbolt pull request #607
Opened 2023-11-11 08:52 UTC by arjunmalhotra1

To keep etcd projects up to date with the latest patch releases & incorporate the latest security updates.

2023-11-11 09:45 UTC, serathius commented
Please sign DCO

2023-11-13 04:15 UTC, arjunmalhotra1 commented
Thanks @serathius. Fixed it.

2023-11-13 05:18 UTC, jmhbnz requested changes
Hey @arjunmalhotra1 - Thanks for raising this, can you also please update:

```bash
cmd/bbolt/README.md:  Go Version: go1.21.1
.github/workflows/tests_windows.yml:          go-version: "1.21.1"
.github/workflows/tests_windows.yml:          go-version: "1.21.1"
```

2023-11-13 05:18 UTC, jmhbnz commented on go.mod
> +go 1.21.4
Hey @arjunmalhotra1 - I don't think it is agreed to start pinning `go.mod` to a specific patch version. The community has only just started discussing it in https://github.com/etcd-io/etcd/issues/16828.

Please keep the `go.mod` at `1.21` for now.

2023-11-13 16:09 UTC, ahrtr commented
Please rebase this PR.

FYI. we just merged https://github.com/etcd-io/bbolt/pull/608. Now we only need to update the go version in one place 
https://github.com/etcd-io/bbolt/blob/master/.go-version#L1

2023-11-13 22:07 UTC, arjunmalhotra1 commented
Thank you @ahrtr I have addressed the issue.

2023-11-13 22:19 UTC, jmhbnz approved these changes
LGTM on green - Thanks @arjunmalhotra1 

Nit - Ideally we would also update `cmd/bbolt/README.md:  Go Version: go1.21.1` but it's not a big deal.

2023-11-14 01:54 UTC, arjunmalhotra1 commented
Thanks @jmhbnz. I have updated in the readme as well.

2023-11-14 03:40 UTC, fuweid approved these changes
LGTM

2023-11-14 12:20 UTC, serathius approved these changes

2023-11-14 12:20 UTC, merged